### ISSUE TITLE
Storage class of invocation id's in openCL

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Headers#1]
[Transferring existing Bugzilla SPIR-V issues here.]

## Bas Nieuwenhuizen 2016-03-23 17:04:09 PDT
I noticed SPIRV-LLVM emitting the GlobalInvocationID Builtin in the UniformConstant storage class.  This surprised me and as that is supposed to be shared across all invocations, while the invocation id is unique per invocation.

So I don't think that that is the correct storage class for the builtin. However Input is only available with Shader Capability, so I don't know a better storage class to put it in.

So what is the correct storage class for GlobalInvocationId? (and related builtins)

Side note:
A lot of the builtins refer to the OpenCL API specification ... which has no mention of them.

## davidnetokhr 2016-03-28 08:27:11 PDT
This is a good question.

UniformConstant is the only non-Shader storage class that's read-only.  However, the spec also says it's OpenCL __constant memory.  That seems a little off, as the number of __constant memory handles can be severely limited by an implementation.

I'll raise this at the working group.

**Comment by raunintc** [comment]
Currently being investigated by the working group

**Comment by johnkslang** [comment]
The **Shader** required capability will be removed the **Input** storage class, so that OpenCL tools can use it for values like invocation ids.

This will be visible in the next published version of SPIR-V 1.0.
