### ISSUE TITLE
Document convention for opcode aliases

### ISSUE THREAD

**Issue by cmarcelo** [KhronosGroup/SPIRV-Headers#108]
SPIR-V 1.4 has added `OpDecorateString`, `OpMemberDecorateString` and `OpUserSemantic` which have the same ID as previously defined operations (from GOOGLE extensions). Would be good to have documented what is the convention to interpret those.

Based on SPIR-V 1.4, it seems like the first one should be considered the main, and any others are aliases.

Alternatively, make this connection as part of the JSON instead of relying on the order.

**Comment by johnkslang** [comment]
The convention and intent is stated in #109; let's follow up there for it.

**Comment by cmarcelo** [comment]
OK, responded there about the convention.

But after that decision, is there a doc or place where these could be written down so we can refer to it? If not, should we create one?

**Comment by johnkslang** [comment]
Yes, there is documentation, and yes it needs to be updated with what we decide about aliasing.

The Khronos registry points to the existing documentation: https://www.khronos.org/registry/spir-v/specs/unified1/MachineReadableGrammar.html. I'll look at moving that to this repository.

**Comment by johnkslang** [comment]
Combing with #109, which will reference discussion here for completeness, and closing this one.
