### ISSUE TITLE
Some literal number operands width underspecified

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/SPIRV-Headers#113]
In `OpTypeInt` the `Width` parameter is clearly specified as a single 32-bit word:

> `Width` specifies how many bits wide the type is. **This literal operand is limited to a single word.** The bit pattern of a signed integer value is two’s complement.

But that's not true for `Signedness`, except perhaps implicitly by virtue of it only listing two valid values; 0 and 1.

In `OpTypeFloat` there's no such specification for the `Width`. I assume it's intended to be the same and always be a single word, but the definition of 'literal number' in the spec leaves it up to the op to specify. Similarly in `OpTypeVector` with the component count, and I image there are probably other cases.

As a related request, it would be useful if these cases where the literal number is a fixed word size were specified in the json grammar. I guess there are backwards compatibility implications to changing them to a different operand kind, but perhaps a new property a la `quantifier` could be added.

**Comment by dneto0** [comment]
To my understanding, all literal number values in the spec are limited to a single 32-bit word except for:
- the words used to specify the value for an OpConstant. (And that instruction is shown as having multiple literal words...)
- The literal values in OpSwitch when the type being selected over is more than 32 bits wide.    This is type-dependent, so an encoding in the JSON grammar would be subtle.

**Comment by johnkslang** [comment]
Maybe there is a small amount of ambiguity there, but it is supposed to tight (and can be fixed where necessary) based on how many physical operands are indicated (1, or more than 1) plus language in the instruction.

The physical operands are always 32-bits, and the if the logical operand could be larger, the instruction should show

A. a variable number of operand slots taken
B. extra language discussing the width

If there is just one operand slot, and nothing else is said, it's just the size of that operand, which is 32 bits.

For example, in **OpConstant**:

> A.  Literal, Literal, ...
> B. ... Types 32 bits wide or smaller take one word. Larger types take multiple words, with low-order words appearing first.

Similarly, but in a more complicated way for **OpSwitch**.

**OpTypeInt** just has one slot for the *Signedness*, with slots always being 32-bits, and the values being either 0 or 1, so there's not much wiggle room there: It's either hex 00000000 or 00000001.

**Comment by johnkslang** [comment]
I'm not sure I see any spec. changes to make here.  Are there any suggestions?

**Comment by baldurk** [comment]
Yes I think I was initially confused by `OpTypeInt` having explicit language saying that the width is a word, and then having it omitted elsewhere. I see what you mean that the word count and operand slots kind of implicitly bound the size of literal numbers anywhere that the word count isn't variable.

I'd say it would be nice if the spec defined literal number explicitly as a 32-bit word if that's the very common use of it, and then make a new definition such as 'context-dependent literal number' (which already exists in the JSON grammar) for the couple of places where it's really needed. I don't know if you want to make that kind of change though.

**Comment by johnkslang** [comment]
This is all made more explicit now, in the just published rev. 2 of SPIR-V 1.5, on the [Khronos SPIR-V Registry](https://www.khronos.org/registry/spir-v/).  "Literal Numbers" are replaced by literals, and each use of literal states its valid values.
