### ISSUE TITLE
Standard has nothing to say about entry point parameters but `spirv-val` disagrees.

### ISSUE THREAD

**Issue by icefoxen** [KhronosGroup/SPIRV-Headers#126]
If I generate a module that contains something like this:

```
OpEntryPoint Fragment %6 "fragment"
%1 = OpTypeFloat 32
...
%5 = OpTypeFunction %1 %1
%6 = OpFunction  %1  DontInline|Pure|Const %5
...
```

...then `spirv-val` declares it invalid with the following error:  `OpEntryPoint Entry Point <id> '6[%6]'s function parameter count is not zero`  It's certainly believable that this is a requirement, however I cannot actually find anything in the SPIR-V reference doc actually stating that an entry point must have no inputs.  Is this an oversight, or is `spirv-val` being overzealous?

Thank you.

**Comment by johnkslang** [comment]
It is up to the client API to have a mechanism or not for passing arguments to the entry-point function.

For Vulkan, for example, we have this in "Appendix A: Vulkan Environment for SPIR-V"

> **Validation Rules within a Module**
>
> A SPIR-V module passed to vkCreateShaderModule must conform to the following rules:
> - Every entry point must have no return value and accept no arguments.

**Comment by icefoxen** [comment]
Aha, thank you!  That clarifies things a lot, I'll have to read the appendices more.  Thanks!
