### ISSUE TITLE
initialization of a global pointer

### ISSUE THREAD

**Issue by AlexeySotkin** [KhronosGroup/SPIRV-Headers#13]
With current version of the spec there is no way to express initialization of a global(program scope) pointer by address if other global variable.

Consider the following OpenCL C code:
```
int v = 0;
global int* p = &v;
```
It can be translated to LLVM as:
```
...
@v = addrspace(1) global i32 0, align 4
@p = addrspace(1) global i32 addrspace(1)* @v, align 4
...
```
LLVM to SPIR-V translator produces the following lines:
```
          ...
          %2 = OpTypeInt 32 0
          %3 = OpConstant %2 0
          %4 = OpTypePointer CrossWorkgroup %2
          %6 = OpTypePointer CrossWorkgroup %4
          %5 = OpVariable %4 CrossWorkgroup %3
          %7 = OpVariable %6 CrossWorkgroup %5
```
The latter OpVariable is initialized by a non-constant instruction, which violates the spec requirement for OpVariable.

[var_addr.ll.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/335173/var_addr.ll.txt)
[var_addr.cl.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/335174/var_addr.cl.txt)
[var_addr.spt.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/335176/var_addr.spt.txt)
[var_addr.spv.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/335175/var_addr.spv.txt)

Seems like #12 and this issue may have the same solution.

**Comment by dneto0** [comment]
I agree this is very similar to #12, just coming from a different angle.
The two issues surfaced here are:

* use-before definition.  (That's solvable already because module-scope OpVariable can be intermixed with constants and types in group 9 of the logical layout).

* the result of an OpVariable is not considered to be a constant.

**Comment by johnkslang** [comment]
Does **OpSpecConstantOp** help? It seems you shouldn't know the address offline, so if it's a run-time constant, that means it's a specialization constant.  Maybe using **OpAccessChain** or **OpPtrAccessChain** as an operand to **OpSpecConstantOp** helps.  I haven't fully internalized the issue yet, just now catching up with some things.

**Comment by johnkslang** [comment]
Khronos has decided on OpVariable can be treated as constant for this purpose, and that will be reflected in revision 6 of 1.0 and revision 2 of 1.1.

**Comment by eddyb** [comment]
> Khronos has decided on OpVariable can be treated as constant for this purpose, and that will be reflected in revision 6 of 1.0 and revision 2 of 1.1.

@johnkslang Is that enough? As far as I've been able to tell, neither `OpConstantComposite` nor `OpSpecConstantComposite` appear to allow `OpVariable`s directly, but LLVM's constants are nested composites with integer/float/pointer leaves.

Is the intention that pointers to other globals, in constant data, have to use noop `OpPtrAccessChain` `OpSpecConstantOp`s to create the pointer? It seems plausible, but I don't see any indication that it's intended.
