### ISSUE TITLE
spirv.hpp uses implementation-defined underlying enum types

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/SPIRV-Headers#14]
The glslang code that uses spirv.hpp causes compiler warnings like:

    /KhronosGroup/glslang/SPIRV/GlslangToSpv.cpp:1973:33: warning: comparison of constant 4294967295 with expression of type 'spv::BuiltIn' is always true [-Wtautological-constant-out-of-range-compare]
                    if (builtIn != spv::BadValue)
                        ~~~~~~~ ^  ~~~~~~~~~~~~~

This is not just a warning but a potential bug. The underlying type of an unscoped enum is an implementation-defined integral type capable of representing all values of the enum. Considering that spv::Builtin only represents a limited number of enum values, the underlying type could be 16-bit or even 8-bit in which case a variable of the enum type will always be unequal to 0xFFFFFFFF (spv::BadValue).

Maybe it would be good to force the enums to be 32-bit by adding a dummy MaxEnum = 0x7FFFFFFF to each enum type.

**Comment by johnkslang** [comment]
Khronos has decided to add `MaxEnum = 0x7FFFFFFF` (or equivalent). This will appear in future revision.
