### ISSUE TITLE
Why is this using a modified version of the MIT license?

### ISSUE THREAD

**Issue by Croydon** [KhronosGroup/SPIRV-Headers#144]
Modifying licenses can cause confusion and a lot of troubles.

What SPIRV-Headers is using is basically the MIT license, but it changes  `the "Software"` to `the "Materials"` and the third paragraph:

> MODIFICATIONS TO THIS FILE MAY MEAN IT NO LONGER ACCURATELY REFLECTS
KHRONOS STANDARDS. THE UNMODIFIED, NORMATIVE VERSIONS OF KHRONOS
SPECIFICATIONS AND HEADER INFORMATION ARE LOCATED AT
   https://www.khronos.org/registry/

Is completely new

1. I don't understand why  `the "Software"` got changed to `the "Materials"`. Maybe this was copied over from a documentation repository or something, but they it should have probably used a well-established license for non-software products. 

2. The third added paragraph sounds like something you might want to add to the file beginning of source files but not really to the `LICENSE` file. The paragraph even refers `TO THIS FILE` which supports my interpretation of this.

**Comment by johnkslang** [comment]
This is from Khronos, not MIT, and from a specification-development activity, not a code-writing activity.

You can read more here: https://www.khronos.org/members/ip-framework

Unless this repo actually contains mistakes relative to what Khronos wants, this is not the place to further discuss Khronos legal subjects.
