### ISSUE TITLE
Reuse enums between opcodes and other enumerants

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/SPIRV-Headers#151]
I think we've misstated something in the reservation file at https://github.com/KhronosGroup/SPIRV-Headers/blob/f8bf11a0253a32375c32cad92c841237b96696c0/include/spirv/spir-v.xml#L90

Because we have only ~65.000 opcodes, but ~4 billion enumerants for other things, and because SPIR-V is designed to support each enum type having its own name space, we should rather be encouraging more dense reservation and use of the opcodes than discouraging it.

It might make sense to uniquely use new enumerants for non opcodes, but not for opcodes.

**Comment by johnkslang** [comment]
We should probably have two reservation spaces, one for opcodes and one for enums.

**Comment by bashbaug** [comment]
> We should probably have two reservation spaces, one for opcodes and one for enums.

+1, This sounds much less error-prone than trying to reuse some enumerants to conserve opcode space.

**Comment by johnkslang** [comment]
See PR #156.

**Comment by johnkslang** [comment]
Closing, as #156 addressed this in April.
