### ISSUE TITLE
OpRayQueryXXX missing from spirv.core.grammar.json

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/SPIRV-Headers#155]
None of the OpRayQueryXXX ops are present as instructions in `include/spirv/unified1/spirv.core.grammar.json` on the master branch (but they are listed in spirv.h and its variants).
   
I'm not sure if this is an oversight or a deliberate omission?  We rely on spirv.core.grammar.json to generate compiler code, and it's a problem for us if instructions are missing.

**Comment by johnkslang** [comment]
Is it that they got renamed to *KHR?

Perhaps both could be there.

cc @dgkoch.

**Comment by stevec611** [comment]
That's strange - I've looked again now and I do see them there.
I don't know what I did wrong earlier …
