### ISSUE TITLE
Transition to using a 'main' branch

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/SPIRV-Headers#173]
We should transition SPIRV-Headers to use a 'main' branch to keep up with the wider changes in the github ecosystem. To give time to prepare for this, I'm proposing we create the 'main' branch on November 2nd and disable commits to the master branch.

Open PRs will need to be re-pointed at the 'main' branch.

**Comment by jeremy-lunarg** [comment]
@dneto0 I believe this has been completed and the issue can be closed.

**Comment by johnkslang** [comment]
Yes, the primary branch is now called `main`, closing.
