### ISSUE TITLE
UniformConstant initialization

### ISSUE THREAD

**Issue by a2flo** [KhronosGroup/SPIRV-Headers#18]
According to "3.7. Storage Class" of the SPIR-V spec, the UniformConstant storage class has the restriction that "Variables declared with this storage class are read-only, and **cannot have initializers**". This clashes with the necessity of constant value/object initialization in OpenCL.
Note that this was only added in SPIR-V Version 1.00, Revision 5, listed as "Khronos SPIR-V issue #56: Clarify that the meaning of "read-only" in the Storage Classes includes not allowing initializers.". The reasoning behind this is unclear (and the issue/report is not public as far as I can tell).

OpenCL example, built with Intel's compiler (same as a SPIRV-LLVM/SPIR toolchain):

```
constant float4 carr[] = {
    (float4)(1.0f),
    (float4)(1.0f),
};

kernel void constant_test(global float4* out) {
    out[get_global_id(0)] = carr[get_global_id(0) % 2];
}
```

violating OpVariable with an initializer marked below:

```
               OpCapability Addresses
               OpCapability Linkage
               OpCapability Kernel
          %1 = OpExtInstImport "OpenCL.std"
               OpMemoryModel Physical32 OpenCL
               OpEntryPoint Kernel %18 "constant_test"
               OpSource OpenCL_C 102000
               OpName %11 "carr"
               OpName %14 "__spirv_BuiltInGlobalInvocationId"
               OpName %19 "out"
               OpDecorate %31 Constant
         %31 = OpDecorationGroup
               OpDecorate %14 BuiltIn GlobalInvocationId
               OpDecorate %11 LinkageAttributes "carr" Export
               OpDecorate %14 LinkageAttributes "__spirv_BuiltInGlobalInvocationId" Import
               OpDecorate %11 Alignment 16
               OpGroupDecorate %31 %11 %14
          %2 = OpTypeFloat 32
          %4 = OpTypeVector %2 4
          %6 = OpTypeInt 32 0
          %8 = OpTypeArray %4 %7
         %10 = OpTypePointer UniformConstant %8
         %12 = OpTypeVector %6 3
         %13 = OpTypePointer UniformConstant %12
         %15 = OpTypeVoid
         %16 = OpTypePointer CrossWorkgroup %4
         %17 = OpTypeFunction %15 %16
         %25 = OpTypePointer UniformConstant %4
          %3 = OpConstant %2 1
          %5 = OpConstantComposite %4 %3 %3 %3 %3
          %7 = OpConstant %6 2
          %9 = OpConstantComposite %8 %5 %5
         %24 = OpConstant %6 0
-->      %11 = OpVariable %10 UniformConstant %9
         %14 = OpVariable %13 UniformConstant
         %18 = OpFunction %15 None %17
         %19 = OpFunctionParameter %16
         %20 = OpLabel
         %21 = OpLoad %12 %14 Aligned 0
         %22 = OpCompositeExtract %6 %21 0
         %23 = OpUMod %6 %22 %7
         %26 = OpInBoundsPtrAccessChain %25 %11 %24 %23
         %27 = OpLoad %4 %26 Aligned 16
         %28 = OpLoad %12 %14 Aligned 0
         %29 = OpCompositeExtract %6 %28 0
         %30 = OpInBoundsPtrAccessChain %16 %19 %29
               OpStore %30 %27 Aligned 16
               OpReturn
               OpFunctionEnd
```

I would presume this restriction on UniformConstant was put in place because of its use in Vulkan/GLSL, where UniformConstant is used for samplers and images (13.1 Vulkan spec), which obviously can't have initializers in Vulkan/GLSL, as well as Input and PushConstant variables which understandably can't have initializers either. So it seems like this restriction on UniformConstant was more of an accident than an intentional change when Input/PushConstant were changed. Also note that glslang is currently emitting Function storage class variables for any constant variables in GLSL, which is spec conformant, but seems unfortunate to me, considering that vendor compilers might want to put this into separate/special read-only memory instead of it eating up registers and not being read-only.

Proposed resolution: refine the restriction on UniformConstant so that only initialization of opaque types is not allowed, with one exception for OpenCL (or LiteralSampler capability), where it's also allowed to initialize OpTypeSampler variables with a OpConstantSampler.

**Comment by johnkslang** [comment]
For the graphics use of **UniformConstant** initializers don't make sense for any type; the values come from the driver/app, not an actual write when the shader runs.  We need to consider how this should appear in OpenCL.  A normal C-like `const` does not map to a shader initialized **UniformConstant**, it's either a literal or a variable that's initialized and then not read from.  Possibly, if there is the right compile-time interface, the C-level initializer turns into a driver-level **UniformConstant** buffer set up (that is how GLSL uses uniform initializers).

**Comment by a2flo** [comment]
Ah, I didn't realize that GLSL uniforms could have initializers. But, reading the GLSL spec and its modification through GL_KHR_vulkan_glsl, it doesn't look like this is allowed any more? "default uniforms" were removed and interface blocks can't have initializers (as well as prohibiting struct nesting). On the other hand, SPIR-V does allow initialization of Uniform variables.

So, what exactly is the preferred/correct way to store module scope constant data in Vulkan/SPIR-V?
For example, if I have a medium sized lookup table filled with constant values (via OpConstant, possibly OpSpecConstant if that is allowed), large enough that it wouldn't fit into registers ("Function memory"), small enough that it would easily fit into uniform memory, which storage class should this use if not UniformConstant? For OpenCL this should obviously be "constant memory" (and thus UniformConstant), but what should it be for Vulkan/SPIR-V? Would a Uniform variable with an OpConstant* initializer and a NonWritable decoration on its struct type make sense?
It would be very odd if there is no equivalent to OpenCL (or other languages) here.

**Comment by johnkslang** [comment]
> Ah, I didn't realize that GLSL uniforms could have initializers.

Yes, but to pass on to other components, not to actually initialize with from a shader at shader-execution time.

> But, reading the GLSL spec and its modification through GL_KHR_vulkan_glsl, it doesn't look like this is allowed any more?

Right.  OpenGL ES never allowed them, and they are not being further propagated.

> SPIR-V does allow initialization of Uniform variables

That should just be for writable ones, like the backing of a buffer block, which a shader is allowed to write to, and so can be initialized.

> So, what exactly is the preferred/correct way to store module scope constant data in Vulkan/SPIR-V?

OpenCL experts may want to chime in (and perhaps an official Khronos answer), but I a high-level language "constant" as being several things:

- just a literal that a front end substitutes at each use, or constant folds with other constants, and this could just be the <id> of a SPIR-V non-specialization constant
- a specialization constant, whose value can be changed just before lowering SPIR-V to the target architecture
- a variable that is effectively read only, but still declared in SPIR-V as a variable that has an initializer and then is never written to

> For example, if I have a medium sized lookup table filled with constant values (via OpConstant, possibly OpSpecConstant if that is allowed), large enough that it wouldn't fit into registers ("Function memory"), small enough that it would easily fit into uniform memory, which storage class should this use if not UniformConstant?

Perhaps it's **UniformConstant**, but all invocations should be using the same constant value, yes? That is, it should not be that every invocation initializes this read-only memory, but that something else put the values in there once, which is then read a very large number of times by invocations, not initialized by them.  This path implies, like the GLSL uniform initializers case, that the initializers take a separate path than the code, so that a driver can setup the **UniformConstant** memory once, for all invocations to read from.

> For OpenCL this should obviously be "constant memory" (and thus UniformConstant), but what should it be for Vulkan/SPIR-V? Would a Uniform variable with an OpConstant* initializer and a NonWritable decoration on its struct type make sense?

This does not yet make sense to me, due to the need for one-time initialization of what should be read only memory from a shader perspective.  Actual use of an initializer in SPIR-V implies a large number of writes from shaders, violating the read-only aspect as well as the set-it-up-once aspect.

**Comment by a2flo** [comment]
> Perhaps it's UniformConstant, but all invocations should be using the same constant value, yes? That is, it should not be that every invocation initializes this read-only memory, but that something else put the values in there once, which is then read a very large number of times by invocations, not initialized by them. This path implies, like the GLSL uniform initializers case, that the initializers take a separate path than the code, so that a driver can setup the UniformConstant memory once, for all invocations to read from.

Yes, exactly that. And to be more specific: this is data built into the binary and already known/constant when calling clCreateProgramWithIL in OpenCL or vkCreateShaderModule on the Vulkan side, or clBuildProgram / vkCreate(Compute|Graphics)Pipelines when initialization from OpSpecConstant is allowed. So it will always be the same data for all kernel/shader executions, thus the driver can set this up once, put it into whichever memory it prefers this to be in and maybe even emit special load instructions for constant memory in the kernel/shader binary.

> OpenCL experts may want to chime in (and perhaps an official Khronos answer), but I see a high-level language "constant" as being several possible things:
> * just a literal that a front end substitutes at each use, or constant folds with other constants, and this could just be the of a SPIR-V non-specialization constant
> * a specialization constant, whose value can be changed just before lowering SPIR-V to the target architecture
> * a variable that is effectively read only, but still declared in SPIR-V as a variable that has an initializer and then is never written to

Yeah, the word "constant" is heavily overloaded ... and all of the above do apply in various contexts.
The need to put it into an OpVariable only exists because user code requested it (in OpenCL at least) or the compiler decides to do so for optimization purposes(*), and because the compiler couldn't constant fold access to it, usually due to accesses only known at run-time (e.g. dynamic index into a lookup table as in the example code listed in the first post). If there was an equivalent to OpAccessChain (and others) that could operate on an OpConstant instead of a pointer, then OpConstants could be used directly instead of needing an OpVariable. Or maybe we just need an OpConstantPointer that can point to / wrap OpConstant data, or a OpConstantVariable. Though solving this within the current form of the spec via UniformConstant memory seems more reasonable to me.


(*) While GLSL doesn't have a language construct for this like OpenCL does, I don't see why a compiler couldn't put global/function "const" data that is actually compile-time constant (as per OpenCL/C/C++ definition) into UniformConstant memory instead of Function memory for optimization purposes. I'd actually expect vendor compilers to already do that if they can. Making this explicit on the SPIR-V/Vulkan side already would of course still be nice.

**Comment by johnkslang** [comment]
The latest release of SPIR-V modified the core spec to no longer disallow initializers for **UniformConstant** storage:

> Variables declared with this storage class are read-only. They may have initializers, as allowed by the client API.

The Vulkan API disallows the initializers, while the OpenCL API allows them.
