### ISSUE TITLE
SPIR-V spec is out of sync

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/SPIRV-Headers#188]
The SPIR-V spec is out of sync with some extensions to the point where it's actively harmful.

![Screenshot at 2021-01-06 19-38-17](https://user-images.githubusercontent.com/521513/103836599-8d6c6480-5057-11eb-8de2-747fab792f45.png)

Eg, this OpTraceRayKHR entry is incorrect, as the last parameter should be a pointer to an OpVariable, not the PayloadID. I was passing the PayloadID. That is not caught by the validator. And it causes a driver segfault. Took 14 days to get the problem diagnosed.

**Comment by dgkoch** [comment]
I think https://github.com/KhronosGroup/SPIRV-Registry/issues would be a better place for this issue, as I'm not aware of any issues with the headers themselves, just the spec (which has the provisional ray tracing semantics listed not the final one). 

I've created an internal Khronos issue for fixing this: https://gitlab.khronos.org/spirv/SPIR-V/-/issues/629

**Comment by dgkoch** [comment]
This should be fixed in SPIR-V 1.5 rev 5.
