### ISSUE TITLE
OpLoopMerge + OpBranchConditional

### ISSUE THREAD

**Issue by a2flo** [KhronosGroup/SPIRV-Headers#19]
According to the description of OpLoopMerge, the loop header block can contain a conditional branch (OpBranchConditional). Doing so would however require the block to contain an OpSelectionMerge in addition to the OpLoopMerge. This is currently not allowed by the spec, because both descriptions state that (OpLoopMerge|OpSelectionMerge) "must be the second-to-last instruction in its block".

E.g. this code is currently invalid:

```
   OpSelectionMerge %selmergebb None
        OpLoopMerge %loopmergebb %continuebb None
OpBranchConditional %condition %true %false
```

Solution: either remove OpBranchConditional from the OpLoopMerge description or refine the "second-to-last" text so that both merge operations can occur in a block.

If doing the latter: shouldn't OpLoopMerge allow OpSwitch as well then?

**Comment by ratchetfreak** [comment]
I'll repeat what I said on the other issue.

The interesting part of a opSelectionMerge is the merge block and whether to flatten the branch. Both of these piece of information (and a bit more) are present in opLoopMerge as the merge block whether to unroll the loop.

Also complicating loops with opSwitch would be a mistake.

You can easily make the loop header be a (non-conditional) opBranch (with standard opLoopMerge) and the first block have a opSwitch where some cases go to the loop's merge block.

in glsl this would look like:

```C
loop: while(true){
    switch(s){
    case 0: //code inside the loop
        break;
    case 1: break loop; //breaks to outside the loop
        //...
    }
    // more code after opSelect's merge block
}
//code after loop's merge block
```

or you can pull the switch to outside the loop:

**Comment by a2flo** [comment]
A OpBranchConditional in the loop header would allow this:
![loop_conditional](https://cloud.githubusercontent.com/assets/439780/18205879/9971a798-7124-11e6-9c3b-ad7af682b3eb.png)
Instead of requiring this:
![split_conditional](https://cloud.githubusercontent.com/assets/439780/18205887/a1cbb1c2-7124-11e6-9992-e3668a78f3d8.png)
with:
```
   OpSelectionMerge %if.end None
        OpLoopMerge %cleanup %if.end None
OpBranchConditional %condition %if.then %if.else
```

And yes, splitting off the conditional branch or switch into a separate block is the obvious workaround for this. Nevertheless, the spec should be fixed, because OpLoopMerge doesn't actually support OpBranchConditional right now, as I said. Note that I'm only mentioning the OpSwitch here for consistency reasons, i.e. if OpBranchConditional is to be allowed in OpLoopMerge, this would also require a change in the OpSelectionMerge text (to allow it next to a OpLoopMerge), but would then also need to mention that it doesn't (or does) support OpSwitch.
(Personally, I don't mind which route you take, just fix it ;))

**Comment by ratchetfreak** [comment]
> Nevertheless, the spec should be fixed, because OpLoopMerge doesn't actually support OpBranchConditional right now

Actually it does support `OpBranchConditional` just with the caveat that one branch must be to the loop's merge block.

Also `OpBranchConditional` without a `opSelectionMerge` is allowed. Never does the spec say that every conditional branch must be preceded by a `op*Merge`. And the example in section 1.9 a for loop is implemented with what is in essence a `if(cond)break;`.

**Comment by a2flo** [comment]
>Actually it does support OpBranchConditional just with the caveat that one branch must be to the loop's merge block.
>
>Also OpBranchConditional without a opSelectionMerge is allowed. Never does the spec say that every conditional branch must be preceded by a op*Merge. And the example in section 1.9 a for loop is implemented with what is in essence a if(cond)break;.

Ah, so you don't actually need OpSelectionMerge at a OpBranchConditional when its merge block would be a block that already is a merge block (and it's directly branching to it)? That would certainly simplify things, and I misread the spec by thinking that all OpBranchConditionals would always create/need a selection construct.

So the following is a perfectly legal structured CFG?
Interestingly, the validator doesn't mind whether "loop.merge" or "exit" is the loop merge block, so I'm still missing something I guess?

![scfg](https://cloud.githubusercontent.com/assets/439780/18209720/4369f038-7135-11e6-80ea-8481ca25b750.png)

**Comment by johnkslang** [comment]
Not all **OpBranchConditional** need a merge, but all those that are heading up a selection construct do.  Merge blocks must be per construct, not shared:

From 2.11:

> * the merge block declared by a header block cannot be a merge block declared by any other header block

From 2.16.2:

> * Selections must be structured, having an **OpSelectionMerge** instruction in their header.

**Comment by a2flo** [comment]
Yes, 2.16.2 is where I got the impression from that all conditionals need a OpSelectionMerge.
So the question is: what is the actual definition of a selection? I would have thought that any kind of conditional/switch would start a new selection, but that's apparently not the case now if such a conditional is part of a larger selection tree iff they all have an edge that goes to a single merge block (defined by the root/top conditional with OpSelectionMerge, or OpLoopMerge), as in my last example CFG. Is my understanding of that correct or are there other cases where you can have a conditional that doesn't need a OpSelectionMerge?

**Comment by johnkslang** [comment]
From 2.11:

> A structured control-flow construct is then defined as one of:
> * a selection construct: the set of blocks dominated by a selection header, minus the set of blocks dominated by the header’s merge block
> * ...

Maybe it seems like circular logic, but I don't think it is.  All control flow must be structured, which means all branches must be accounted for by one of the listed structured constructs.  But, that doesn't mean all branches have to initiate such a construct; they can also be involved in terminated them.
