### ISSUE TITLE
Any chance to make new release?

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/SPIRV-Headers#199]
New sdk vulkan seems needs what is now above last tagged release.

It would be good to see better coordination about releasing stuff between spirv-* and vulkan-* repos.

**Comment by kloczek** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/issues/4237

**Comment by AndreyMlashkin** [comment]
New releases would be appreciated. Could you please just tag a new version periodically?

**Comment by AndreyMlashkin** [comment]
@svenvh
@shrekshao
@RafaelCintron

**Comment by kloczek** [comment]
New vulkan sdk has been released and still no new release :(

**Comment by Oxalin** [comment]
Commit cf00fad5 should have been tagged at least since it is the minimal commit to successfully build SPIRV-Tools 2021.1 and 2021.2.

See https://github.com/KhronosGroup/SPIRV-Tools/issues/4366

**Comment by mattst88** [comment]
Please make a new release. This is super annoying for Linux distributions.

**Comment by mattst88** [comment]
@dneto, @dnovillo, @kuhar: I'm trying to update SPIRV and Vulkan packages in ChromeOS, and SPIRV-Tools releases at least the last few months have depended on SPIRV-Headers changes that are in no tagged releases. I guess @johnkslang was making the releases here before he retired—could we figure out who can push the occasional git tag from now on?

**Comment by dnovillo** [comment]
> @dneto0, @dnovillo, @kuhar: I'm trying to update SPIRV and Vulkan packages in ChromeOS, and SPIRV-Tools releases at least the last few months have depended on SPIRV-Headers changes that are in no tagged releases. I guess @johnkslang was making the releases here before he retired—could we figure out who can push the occasional git tag from now on?

I am not sure whether anyone is in charge of producing SPIRV-Header releases.  When we (Google) do SPIRV-Tools releases, we base them on the SPIRV-Headers git hash that happens to be in `DEPS` at the time.  So, in that sense, the SPIRV-Headers release is defined by the value of `spirv_headers_revision` inside `DEPS` in the release branch (this may not be ideal).

@alan-baker tells me that SPIRV-Headers is updated from time to time (mostly when SPIRV-Tools doesn't build).

@s-perron, @alan-baker  would it make sense for us to tag SPIRV-Headers when we tag SPIRV-Tools releases?

**Comment by mattst88** [comment]
> > @dneto0, @dnovillo, @kuhar: I'm trying to update SPIRV and Vulkan packages in ChromeOS, and SPIRV-Tools releases at least the last few months have depended on SPIRV-Headers changes that are in no tagged releases. I guess @johnkslang was making the releases here before he retired—could we figure out who can push the occasional git tag from now on?
> 
> I am not sure whether anyone is in charge of producing SPIRV-Header releases. When we (Google) do SPIRV-Tools releases, we base them on the SPIRV-Headers git hash that happens to be in `DEPS` at the time. So, in that sense, the SPIRV-Headers release is defined by the value of `spirv_headers_revision` inside `DEPS` in the release branch (this may not be ideal).

Understood, thanks for replying and @-ing the appropriate people. For me, as a Linux distro maintainer, and as a Google employee who needs to update SPIRV/Vulkan packages in ChromeOS from time to time, having tagged releases greatly simplifies the process.

**Comment by mattst88** [comment]
Ping?

Concretely I'd suggest that when SPIRV-Tools is tagged, the SPIRV-Headers SHA1 in SPIRV-Tools' `DEPS` file also be tagged with the same release version. E.g., in SPIRV-Tools v2021.2 `spirv_headers_revision` was `07f259e68af3a540038fa32df522554e74f53ed5`, so we could simply tag that SHA1 as v2021.2 of SPIRV-Headers. Would be great to make that tag, even now.

**Comment by dnovillo** [comment]
There is still no resolution for this, but I understand that the SPIR-V WG is discussing it this week.

**Comment by kloczek** [comment]
Still no new release .. what is going on?

**Comment by AndreyMlashkin** [comment]
@johnkslang @raunraun @greg-lunarg @MarijnS95 @NikitaRudenkoIntel @gnl21
could someone of you please create a new tag?

**Comment by kloczek** [comment]
> @johnkslang @raunraun @greg-lunarg @MarijnS95 @NikitaRudenkoIntel @gnl21
> could someone of you please create a new tag?

.. or at lease explain what is going on here and why there is no new release?🤔

**Comment by raunraun** [comment]
We discussed internally and propose to adopt the tagging mechanism of the Vulkan SDK in this repo and a few others that are not currently tagged.

**Comment by kloczek** [comment]
> We discussed internally and propose to adopt the tagging mechanism of the Vulkan SDK in this repo and a few others that are not currently tagged.

Whatever .. 
Still no new release :(
My PR which provides SPIRV-Headers.pc pkgconfig file has been merged however without first release with that change pushing to other packkages PRs checking SPIRV-Headers available in build env version still cannot be done.

Rwally .. where is the problem with run just one `<censored>` git tag command?🤔

**Comment by kloczek** [comment]
BTW just found that despite fact that last git tag is `1.5.4.raytracing.fixed` in CMakeLists.txt still is `1.5.1`
https://github.com/KhronosGroup/SPIRV-Headers/blob/master/CMakeLists.txt#L32

**Comment by MarijnS95** [comment]
It appears a tag/"release" has now been made, but this issue wasn't pinged?

https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/sdk-1.2.198.0

**Comment by greg-lunarg** [comment]
Ping.

Indeed, https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/sdk-1.2.198.0 has been created in response to this issue.

We believe this issue can now be closed, Please let us know if anything else is required.

**Comment by ArchangeGabriel** [comment]
So what should be the proper version number now? Because the tag is sdk-1.2.198.0, but [the commit it points to](https://github.com/KhronosGroup/SPIRV-Headers/commit/c8213b3c5a2cf3a0f5c4d1e7d7b8fc2ac9f4806d) sets 1.5.5 as the new version (previous one was 1.5.4).

**Comment by greg-lunarg** [comment]
Previously, the SPIRV-Headers tags have followed the version of the SPIR-V spec they implement, but I don't think that is a good practice going forward since the SPIRV-Headers repo changes much more frequently (daily) than the SPIR-V spec version (yearly).

I think it is good to continue to include the SPIR-V spec version in the SPIRV-Headers version. I see a couple ways to do that.

My preferred solution is to add a tweak number to the end of the SPIR-V spec version (1.5.5) going forward. So I would propose making the next SPIRV-Headers version tag 1.5.5.0.

I know this is not completely consistent with semantic versioning. Can everyone deal with this format?

The other option is to pretend there is an implicit dot and call the next SPIRV-Headers version 1.5.500.

**Comment by ArchangeGabriel** [comment]
@greg-lunarg Sorry for the lack of answer. Actually as the question was packaging oriented, the correct answer was “switch to sdk version” and that is fine. As linked issues show, other distros started to do so, and so will Arch. And since new tags are added here with each sdk release, we can consider this as completely solved.
