### ISSUE TITLE
The value of OpMax is incorrect

### ISSUE THREAD

**Issue by amdrexu** [KhronosGroup/SPIRV-Headers#20]
The SPIR-V binary use 16 bits to store the OpCode. Thus, the limit of OpCode should be OpMax = 0xffff instead of OpMax = 0x7fffffff.

**Comment by johnkslang** [comment]
This was done to ensure the C++ compiler used 32-bit types, and I'm unclear that it is necessary to restrict the actual enum type this way, even though once everything is packed together the first 32-bit word is a combination of a size and one of these enumerants.  Perhaps it is a bad name in this case, but it's the convention being used in all the enums.

There are also ceilings used in some tools that track the actual maximum enumerant they want to represent (e.g., 321 for opcodes, not even 0xffff).

**Comment by amdrexu** [comment]
Thank you. I understand it now. I will close this issue ticket.
