### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by JulioSordi** [KhronosGroup/SPIRV-Headers#203]
Can't install spirv-headers in Kubuntu 20.04

`cmake .. CMake Error: The source directory "/home/julio" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI.

cmake --build . --target install Error: could not load cache`

**Comment by raunraun** [comment]
This appears to be pointing cmake at a wrong directory.  Please reopen if necessary.
