### ISSUE TITLE
Add `SPV_NV_bindless_texture` extension

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Headers#239]
The intstructions, capability, etc from the extension are not included in the spirv grammar. Would be nice to have for support in  spirv-tools and other libraries.

Specification: https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/NV/SPV_NV_bindless_texture.asciidoc

**Comment by raunraun** [comment]
Poke @dgkoch @jeffbolznv

**Comment by dgkoch** [comment]
cc @pmistryNV  

The grammar support was added in https://github.com/KhronosGroup/SPIRV-Headers/pull/248

See https://github.com/KhronosGroup/SPIRV-Tools/pull/4597 for the spirv-tools support, so I think we can probably close this.

**Comment by msiglreith** [comment]
Great, thanks!
