### ISSUE TITLE
Reserve opcodes

### ISSUE THREAD

**Issue by James-Jones** [KhronosGroup/SPIRV-Headers#24]
Please allocate 64 opcode entries for IMG.

**Comment by johnkslang** [comment]
Would you be willing to submit a PR that makes the desired change against include/spirv/spir-v.xml?  The comments in that file have the instructions/rules to follow for making the allocation.  Thanks.

(Alternatively, post the line here that makes the allocation you want.)

**Comment by James-Jones** [comment]
<ids type="opcode" start="5504" end="5567" vendor="Imagination"/>

**Comment by johnkslang** [comment]
I added this in bd47a9abaefac00be692eae677daed1b977e625c, as well as reserving vendor ID 12 for Imagination.
