### ISSUE TITLE
1.5.5 tag is missing?

### ISSUE THREAD

**Issue by kanavin** [KhronosGroup/SPIRV-Headers#252]
Has 1.5.5 been released? If so, the git tag for it that points to the right commit is missing.

**Comment by mattst88** [comment]
I think the tag is `sdk-1.2.198.0`. See https://github.com/KhronosGroup/SPIRV-Headers/issues/199#issuecomment-977265693

**Comment by kanavin** [comment]
Thanks, I made the needed adjustments locally.
