### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by bl4ckb0ne** [KhronosGroup/SPIRV-Headers#266]
SPIRV-Tools recently release [v2022.1](https://github.com/KhronosGroup/SPIRV-Tools/releases/tag/v2022.1) depending on [b42ba6d92faf6b4938e6f22ddd186dbdacc98d78](https://github.com/KhronosGroup/SPIRV-Tools/blob/v2022.1/DEPS#L9).

The latest tagged release was a few month ago, and it would make packaging much easier.

Thanks.

**Comment by Nuc1eoN** [comment]
I am also confused by the naming scheme in https://github.com/KhronosGroup/SPIRV-Headers/tags

What is the most recent stable currently? Is it `1.5.4` or is it `sdk-1.3.204.0`?

**Comment by eero-t** [comment]
IMHO there should be release notes explaining this (and how the new version relates to tags in the related SPIRV projects).

But at least there are now new, *matching* tags for both SPIRV-Headers and SPIRV-Tools. :-)

**Comment by Nuc1eoN** [comment]
Leaving it as an opbjective experience/feedback here, as a package maintainer packaging spirv-* related stuff so far, has been a pain in the butt :)

**Comment by bl4ckb0ne** [comment]
b42ba6d92faf6b4938e6f22ddd186dbdacc98d78 has been released under the [sdk-1.3.204.0 ](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/sdk-1.3.204.0) tag. It's not perfect but at least there's something to package. It looks like the "new" version number follow what Vulkan does, might be easier to track.
