### ISSUE TITLE
When does OpTypeImage use an access specifier?

### ISSUE THREAD

**Issue by mleise** [KhronosGroup/SPIRV-Headers#27]
I'm new to SPIR-V and OpenCL and found the description of OpTypeImage unclear. It says is that the access specifier parameter is optional without constraints, but all the access specifiers depend on the _Kernel_ capability. Does that imply that image types with an access specifier must only be used in _Kernel_ execution modes and those without must only be used in other execution modes?
That definition would fit into a larger picture since there is no mention of a default access specifier and when access specifiers are used on OpTypeImage they are accompanied by the _ImageBasic_ and _ImageReadWrite_ capabilities that also depend on _Kernel_.

P.S.: Also since we can have multiple entry points with different execution modes, the question can be asked if it is valid to have access specifiers on an image type that is used in both _Kernel_ and non-_Kernel_ execution modes. In other words, is the access specifier allowed and silently ignored in non-_Kernel_ execution modes?

**Comment by johnkslang** [comment]
Vulkan does not allow the **Kernel** capability to be declared in a SPIR-V module.

Use of an *Access Qualifier* would require declaring the **Kernel** capability, so would be invalid in a Vulkan SPIR-V module.

**Comment by mleise** [comment]
Thanks for the clarification. I falsely assumed that SPIR-V would unify shader and kernel programs for the APIs that support it. After cross-reading the relevant parts of OpenCL and Vulkan it is now clear to me that **Kernel** is strictly OpenCL and **Shader** is strictly for graphics APIs. As such it is practically up to the OpenCL C/C++ compiler if and how to use an _Access Qualifier_.
