### ISSUE TITLE
As per SPV_KHR_ray_tracing spec minimum version SPIRV should be 1.4

### ISSUE THREAD

**Issue by pmistryNV** [KhronosGroup/SPIRV-Headers#275]
As per SPV_KHR_ray_tracing spec minimum version required is 1.4 however all the enums defined in spirv.core.grammar.json don't have the version explicitly defined as 1.4.
How does the spirv validator then validates this requirement?

**Comment by alan-baker** [comment]
The version fields in the grammar are only for inclusions in core SPIR-V. So if SPV_KHR_ray_tracing were integrated into the core specification in say SPIR-V 1.8, then those enumerants would get 1.8 listed in the grammar at that point. Until then the validator would have to add some code that when it sees `OpExtension "SPV_KHR_ray_tracing"` it would need to validate that the binary version is 1.4 or later.
