### ISSUE TITLE
OpSubgroupReadInvocationKHR missing in SPIR-V 1.1 spirv.h

### ISSUE THREAD

**Issue by BNieuwenhuizen** [KhronosGroup/SPIRV-Headers#28]
OpSubgroupReadInvocationKHR, defined by https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_shader_ballot.html to be 4432 is missing in the spirv.h header in this repository.

**Comment by johnkslang** [comment]
This is fixed in the just released revisions.
