### ISSUE TITLE
Build error regarding 'SpvBuiltInCullMaskKHR'

### ISSUE THREAD

**Issue by aabdolrashidi** [KhronosGroup/SPIRV-Headers#280]
Building vulkan-deps from SPIRV-Tools and SPIRV-Headers is failing due to the error below:

error: enumeration value 'SpvBuiltInCullMaskKHR' not handled in switch [-Werror,-Wswitch]
switch (label) {
^~~~~
Even though the case is already included in commit https://github.com/KhronosGroup/SPIRV-Tools/commit/58dc37ea6af7ec09f32f7b13ff60071e3ba2bd24. It is possible that SPIRV-Tools and SPIRV-Headers are out of sync.

More info: [Here](https://bugs.chromium.org/p/angleproject/issues/detail?id=7273)
CC: @ewerness-nv @dgkoch

**Comment by dgkoch** [comment]
Yeah - spirv-tools hasn't been updated yet. I'll try to get the patch pushed today.

**Comment by aabdolrashidi** [comment]
Sounds good! Thank you.

**Comment by dgkoch** [comment]
Spirv-tools support: https://github.com/KhronosGroup/SPIRV-Tools/pull/4792 Please follow that issue.
