### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_INCLUDEDIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [KhronosGroup/SPIRV-Headers#282]
As per title: `SPIRV-Headers.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_INCLUDEDIR`. This leads to broken .pc files on NixOS in particular.

Morally identical to https://github.com/KhronosGroup/SPIRV-Tools/issues/3905. See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by johnkslang** [comment]
Is there a specific way you'd like to see this fixed, or do you have a PR you could propose?

**Comment by juan-lunarg** [comment]
`CMAKE_INSTALL_INCLUDEDIR` shouldn't be an absolute path. Or at least nothing in the CMake docs suggest setting `CMAKE_INSTALL_INCLUDEDIR` as an absolute path is a good idea.

**Comment by juan-lunarg** [comment]
Sorry turns out I was wrong. I'll make a PR to fix this for spirv-headers and spirv-tools.

Link to CMake docs:
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

```
CMAKE_INSTALL_<dir>

Destination for files of a given type. This value may be passed to the DESTINATION options of [install()](https://cmake.org/cmake/help/latest/command/install.html#command:install) commands for the corresponding file type. It should typically be a path relative to the installation prefix so that it can be converted to an absolute path in a relocatable way (see CMAKE_INSTALL_FULL_<dir>). However, an absolute path is also allowed.
```

The main line of focus being:

> It should typically be a path relative to the installation prefix so that it can be converted to an absolute path in a relocatable way (see CMAKE_INSTALL_FULL_<dir>). However, an absolute path is also allowed.

**Comment by juan-lunarg** [comment]
Thanks for reporting this @alexshpilkin sorry for being wrong initially.

This is now fixed and tested as part of the CI process.
