### ISSUE TITLE
Add SPIR-V 5 byte module header size to header file

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/SPIRV-Headers#297]
from: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4634#discussion_r992749426

Would be nice to have a constant value in the headers to use for code who needs to skip to first instruction without just having a magic `5` in their code

**Comment by johnkslang** [comment]
E.g., your code currently says

```
 it += 5;  // skip first 5 word of header
```

You could replace that with, if nothing else,

```
 it += 1; // magic number
 it += 1; // version number
 it += 1; // generator magic number
 it += 1; // instruction bound
 it += 1; // schema
```

**Comment by sjfricke** [comment]
Thinking more about it, I agree that your above suggestions is just as good of a solution
