### ISSUE TITLE
for C++11, define & overloads for mask enum types

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Headers#303]
The overloads for | are already defined, but it would be useful to have & overloads as well.

**Comment by dneto0** [comment]
For example, this exists:

```
inline ImageOperandsMask operator|(ImageOperandsMask a, ImageOperandsMask b) { return ImageOperandsMask(unsigned(a) | unsigned(b)); }  
```

But it would be nice to have the corresponding overload for &

**Comment by dneto0** [comment]
And xor too.

**Comment by alan-baker** [comment]
2022-12-14 WG agreed this is a good idea and should do this.
