### ISSUE TITLE
doc: Missing description for OpGroupNonUniformPartitionNV

### ISSUE THREAD

**Issue by mmoult** [KhronosGroup/SPIRV-Headers#310]
According to the spec, `OpGroupNonUniformPartitionNV` is currently reserved, but not defined (see https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformPartitionNV). However, as @greg-lunarg pointed out:

> "Looking at the spec for the GLSL extension GL_NV_shader_subgroup_partitioned, subgroupPartitionNV maps directly to OpGroupNonUniformPartitionNV, so it seems OpGroupNonUniformPartitionNV is well defined."

(See https://github.com/KhronosGroup/glslang/issues/3085 for reference.)

The registry home page indicated that feedback should be posted to this repository.

**Comment by dgkoch** [comment]
This is how extension functionality is denoted in the core specification. 

OpGroupNonUniformPartitionNV is fully documented in the SPV_NV_shader_subgroup_partitioned extension specification. 
See http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/NV/SPV_NV_shader_subgroup_partitioned.html

**Comment by mmoult** [comment]
Thank you for the quick response!

Yes, I see that many other operations have the same form of "Reserved" on the right and "TBD" in the description. I assumed that "TBD" stood for "to be determined", which would mean to be that it is not fully cemented.

Thank you for the link to the extension specification. The description there was helpful. I noticed that the status is "Draft" instead of "Complete". Is there something holding this instruction back from being completed, or does the page just need to be updated?

**Comment by dgkoch** [comment]
Marked [SPV_NV_shader_subgroup_partitioned](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/NV/SPV_NV_shader_subgroup_partitioned.html) as complete via https://github.com/KhronosGroup/SPIRV-Registry/pull/184 

Closing as I don't think there is anything else to do here. Reopen if you disagree.
