### ISSUE TITLE
Duplicate capability constant

### ISSUE THREAD

**Issue by doe300** [KhronosGroup/SPIRV-Headers#32]
In `include/spirv/1.1/spirv.h`, the value 4433 is used for two enum values (lines 637+)

    SpvCapabilityStorageBuffer16BitAccess = 4433,
    SpvCapabilityStorageUniformBufferBlock16 = 4433,

It looks like the `SpvCapabilityStorageBuffer16BitAccess` should be 4432.

Same error on the next two lines:

    SpvCapabilityStorageUniform16 = 4434,
    SpvCapabilityUniformAndStorageBuffer16BitAccess = 4434,

**Comment by johnkslang** [comment]
Both these pairs are intentionally aliased, and the value 4432 is currently intentionally unused.

(The introduction of the **StorageBuffer** storage class motivated additional names for the same enum value.)

You, or tools you write, are welcome to use one or both names, depending on the situation.  Obviously, a switch statement would need to pick just one. (SPIR-V is technically specified by the binary number.)
