### ISSUE TITLE
Update to `actions/checkout@v3`

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/SPIRV-Headers#325]
If you look at the actions for CI it's warning about deprecated functionality:

https://github.com/KhronosGroup/SPIRV-Headers/actions/runs/4366849935

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

The fix is very simple. Just update to `actions/checkout@v3`

**Comment by kpet** [comment]
I recommend setting up Dependabot to manage this: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot. It can be configured to automatically create PRs to migrate actions to their latest version.
