### ISSUE TITLE
Crash in OpVectorShuffle when Component literal is FFFFFFFF

### ISSUE THREAD

**Issue by w0wtiger** [KhronosGroup/SPIRV-Headers#33]
Hello. I tried the code.

```
GLSL:
  vec4 v;
  v.x = 1.0;
Vulkan:
  VectorSuffle 1 1 2 -1 -1 -1
```

but it crashed in [index_to_swizzle].
I see SPIR-V Specification 1.00.

`A Component literal may also be FFFFFFFF, which means the corresponding result component has no source and is undefined.`

Could spirv_glsl not be implemented about FFFFFFFF?

**Comment by johnkslang** [comment]
Can you say which software component crashed? Thanks.

**Comment by w0wtiger** [comment]
Sorry. I reported on wrong site.
I wrote Mesa IR to SPIR-V.
Then I tried SPIR-V to GLSL (spirv_glsl.cpp) at [KhronosGroup/SPIRV-Cross].

Thank you.
