### ISSUE TITLE
Missing support for AMD extensions

### ISSUE THREAD

**Issue by cwabbott0** [KhronosGroup/SPIRV-Headers#36]
The current public SPIR-V headers are missing headers/json for SPV_AMD_shader_ballot, SPV_AMD_shader_trinary_minmax, SPV_shader_explicit_vertex_parameter, and SPV_AMD_gcn_shader. Since at least one shipping game (DOOM) uses some of these extensions in Vulkan, we plan to implement these extensions in Mesa for radv. Since Mesa uses the C versions of the headers, and the only public version of the AMD extensions header (in glslang) is the C++ version, this means we'll have to ship modified (non-Khronos-official) versions of the SPIR-V headers in Mesa, which seems unfortunate.

**Comment by dneto0** [comment]
There is work in progress to add these AMD-specific tokens to the standard headers.

**Comment by dneto0** [comment]
See original https://github.com/KhronosGroup/SPIRV-Headers/pull/37 which is being integrated via Khronos-internal processes.

**Comment by cwabbott0** [comment]
Thanks! It seems that the changes to spirv.h have landed in the public repo, but GLSL.ext.AMD.h with the defines for the extended instructions is still missing. In the meantime, I've hacked up the glslang copy of that header to be C-compatible. I'll try to figure out the Khronos process to get that released when I get closer to landing support in Mesa. Or maybe by then, it'll already have landed and I won't have to do anything :)

**Comment by dneto0** [comment]
This would be the first case of an extended instruction set C header for a *vendor* extension.  I haven't heard of any request by AMD to add that to SPIRV-Headers; I don't know how they want users to get the header.

**Comment by johnkslang** [comment]
Note the following are present:

- SPV_AMD_shader_ballot
- SPV_AMD_shader_explicit_vertex_parameter

If other AMD-specific tokens are missing, is there a path to ask them what to add?  It seems this should be assigned there.

**Comment by amdrexu** [comment]
First, we define extended instructions to avoid inserting new semantics to core grammar. Later, we find some KHR extensions define new OpCodes directly without extended instructions involved. So this strategy is obsoleted. I am not sure if there are good ways introducing such missing tokens in standard SPIR-V header. Or, maybe we should publish the AMD-private header GLSL.ext.AMD.h in SPIRV-headers.
