### ISSUE TITLE
Commit broke VVL: spirv_grammar_generator.py

### ISSUE THREAD

**Issue by amaiorano** [KhronosGroup/SPIRV-Headers#373]
Please see my comment here: https://github.com/KhronosGroup/SPIRV-Headers/commit/c6e625d2c969dfc03965e9d80221ead48bb03795#r125406052

This line breaks VVL builds, specifically when spirv_grammar_generator.py runs, it will fail [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/scripts/generators/spirv_grammar_generator.py#L151).

The IdScope "name" field should be either Execution or Memory (or Scope, though that's a wrong name according to the comments).

Our internal google build failed with:
```
[40|47] Generating spirv_grammar_helper.h
ERROR: unknown operand OpInitializeNodePayloadsAMDX not handled correctly
```

**Comment by amaiorano** [comment]
I opened a similar issue on the VVL repo, as I believe it is probably something that needs fixing in their generator script. If so, then please close this issue.

**Comment by spencer-lunarg** [comment]
this is a validation layer bug, will fix it there
