### ISSUE TITLE
Inconsistent documentation for LiteralInteger

### ISSUE THREAD

**Issue by programmerjake** [KhronosGroup/SPIRV-Headers#38]
in [spirv.core.grammar.json](https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/1.2/spirv.core.grammar.json#L5605) the `doc` describes a `LiteralInteger` as "An integer consuming one or more words", however, in [`SPV_OPERAND_TYPE_LITERAL_INTEGER` in SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L110), the documentation describes it as always a 32-bit word. Which is correct, or, are they not even the same thing?

Additionally, if a `LiteralInteger` does use more than one word, where is it used that way?

**Comment by johnkslang** [comment]
The real source for clarifying such things is the specification. In this case, the specification is clear. For the definition:

> *Literal Number*: A numeric value consuming one or more words. An instruction will determine what type a literal will be interpreted as. When the type’s bit width is larger than one word, the literal’s low-order words appear first. When the type’s bit width is less than 32-bits, the literal’s value appears in the low-order bits of the word, and the high-order bits must be 0 for a floating-point type, or 0 for an integer type with Signedness of 0, or sign extended when Signedness is 1. (Similarly for the remaining bits of widths larger than 32 bits but not a multiple of 32 bits.)

Later, for example, **OpConstant** makes a single scalar, taking literal operands, with the specification saying:

> *Value* is the bit pattern for the constant. Types 32 bits wide or smaller take one word. Larger types take multiple words, with low-order words appearing first.

I guess a tool might have domain restrictions, simplifications, incorrect comments, or defects, and specific-case issues should redirect to them.

**Comment by programmerjake** [comment]
The problem with your answer is that a `LiteralInteger` is not the same as a _Literal Number_:
- `OpExtInst` uses `LiteralExtInstInteger` for **Instruction**, a _Literal Number_
- `OpSpecConstantOp` uses `LiteralSpecConstantOpInteger` for **Opcode**, also a _Literal Number_
- `OpConstant` uses `LiteralContextDependentNumber` for **Value**, a _Literal_

I reported the problem here because Dave Airlie (@airlied) (the main developer of RADV, an unofficial Vulkan driver for AMD GPUs) had said that he didn't know of any spots where a `LiteralInteger` needed multiple words, so I think that the [comment on `SPV_OPERAND_TYPE_LITERAL_INTEGER` in SPIRV-Tools](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L110) is correct and the `doc` string in the json file here is incorrect.

**Comment by johnkslang** [comment]
These are a convention layered on the spec., for some of the the *Literal Numbers* I quoted spec language about that are integers.

Looking through the layers,  **OpSwitch** can have an integer literal that takes more than one word. In the JSON grammar layers, **OpSwitch** takes a `PairLiteralIntegerIdRef`, which is expressed in terms of `LiteralInteger`.

**Comment by programmerjake** [comment]
I'm closing this issue because there isn't any problem with either SPIRV-Headers or SPIRV-Tools. SPIRV-Tools uses `SPV_OPERAND_TYPE_VARIABLE_LITERAL_INTEGER_ID` for __OpSwitch__, I had thought it used `SPV_OPERAND_TYPE_LITERAL_INTEGER` instead.

**Comment by eddyb** [comment]
> I'm closing this issue because there isn't any problem with either SPIRV-Headers or SPIRV-Tools. SPIRV-Tools uses `SPV_OPERAND_TYPE_VARIABLE_LITERAL_INTEGER_ID` for **OpSwitch**, I had thought it used `SPV_OPERAND_TYPE_LITERAL_INTEGER` instead.

Did something change? [The current `SPIRV-Tools` code](https://github.com/KhronosGroup/SPIRV-Tools/blob/35fd0e17d081b28a0ff15b376329205c20c7d1f8/source/binary.cpp#L529-L541) is pretty clear on `OpSwitch` using `SPV_OPERAND_TYPE_LITERAL_INTEGER`, I'm guessing through [this decomposition](https://github.com/KhronosGroup/SPIRV-Tools/blob/0c4deebc966b4e3dc29e0c8504959eff7b11f691/include/spirv-tools/libspirv.h#L240-L244).

In effect, SPIRV-Tools works around the JSON *misusing* `LiteralInteger` in the definition of `PairLiteralIntegerIdRef`, but [other than that `LiteralInteger` is always 32 bits](https://github.com/KhronosGroup/SPIRV-Tools/blob/0c4deebc966b4e3dc29e0c8504959eff7b11f691/include/spirv-tools/libspirv.h#L131).
