### ISSUE TITLE
1.3.268.0: change in tagging convention?🤔

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/SPIRV-Headers#387]
Up to now sdk versions have been tagged as `sdk-<version>`.
1.3.268.0 looks like has been tagged as `vulkan-sdk-<version>`.
Mistake or from now it will be always like this? 🤔 

I'm asking because my automation failed automatically upgrade package because this change.

**Comment by juan-lunarg** [comment]
> Up to now sdk versions have been tagged as sdk-<version>.
1.3.268.0 looks like has been tagged as vulkan-sdk-<version>.
Mistake or from now it will be always like this? 🤔

The new convention is indeed vulkan-sdk-\<version\> this was documented in other repos like Vulkan-Headers.
https://github.com/KhronosGroup/Vulkan-Headers

**Comment by kloczek** [comment]
OK. Closing 👍
