### ISSUE TITLE
Unable to update to spirv-llvm-translator 18.1.0, possible due to too old SPIRV-Headers

### ISSUE THREAD

**Issue by TimB87** [KhronosGroup/SPIRV-Headers#422]
Hi,

trying to update CRUX 3.7 to LLVM 18.1.0 and hit a road blocker with SPIRV-LLVM-Translator, possibly due to too old headers:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2415

We are currently deploying vulkan-sdk-1.3.275.0 for SPIRV-Headers.

**Comment by daurnimator** [comment]
There indeed seems to be a missing tag on commit 8b246ff75c6615ba4532fe4fde20f1be090c3764

It's also used by spirv-tools: https://github.com/KhronosGroup/SPIRV-Tools/compare/v2023.6.rc1...v2024.1.rc1#diff-4cc955bcf0b472353786cc8d8b7d346fb432c091bed099de884885e938392814R16

**Comment by TimB87** [comment]
since KhronosGroup/SPIRV-LLVM-Translator#2415 is resolved, I will close this ticket. Again, thanks for everybody involved :-)
