### ISSUE TITLE
Missing SelectionControl value

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Headers#43]
According to the SPIR-V 1.2 specification, SelectionControl has three possible values:

0x0 None
0x1 Flatten
0x2 DontFlatten

However, in https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/1.2/spirv.json only two values are provided:

"Flatten": 0,
"DontFlatten": 1

Looks like spirv.json is wrong

**Comment by johnkslang** [comment]
Your first set of numbers are mask values. The json numbers are bit numbers. E.g., for "DontFlatten":

```
0x2 == 1 << 1
```

Other headers have both bit numbers and mask values, but the .json file has only the bit numbers.

**Comment by afd** [comment]
Thanks for clarifying!
