### ISSUE TITLE
Create release that matches spire-tools 2024.3 release

### ISSUE THREAD

**Issue by ZzEeKkAa** [KhronosGroup/SPIRV-Headers#438]
spirv-tools 2024.3 requires `2acb319af38d43be3ea76bfabf3998e5281d8d12` commit. Is it possible to create release from this commit?

What is the dependency between headers and tools? Is possible to have headers release that is compatible with spirv-tools releases in the future?

Currently, It breaks condo build (and may be others) https://github.com/conda-forge/spirv-tools-feedstock/pull/15 . I believe that headers version mismatch is the reason.

**Comment by jeremy-lunarg** [comment]
For the Vulkan SDK, we create a set of tags (e.g. vulkan-sdk-1.3.290.0) for all source repos. Would it work for you to update against the SDK release cadence? We also perform additional testing against the SDK releases.

**Comment by bashbaug** [comment]
@ZzEeKkAa will using the Vulkan SDK tags work for you?  We're interested in your feedback - thanks!

Note also that spirv-tools includes a [DEPS](https://github.com/KhronosGroup/SPIRV-Tools/blob/main/DEPS) file describing the version requirements for its dependencies that may be useful.

**Comment by ZzEeKkAa** [comment]
I guess there was an issue that `vulkan-sdk-1.3.290.0` was not tagged, and spirv-tools 2024.3 was already tagged. In conda forge you can distribute only tagged libraries.

https://github.com/KhronosGroup/SPIRV-Tools/blob/main/DEPS works good, but it requires manually checking what is the release version for this commit. Ideally I would want somehow to get the headers version, not the commit hash.
