### ISSUE TITLE
SubgroupLocalInvocationId and SubgroupSize should list SubgroupBallotKHR

### ISSUE THREAD

**Issue by ianromanick** [KhronosGroup/SPIRV-Headers#44]
GL_ARB_spirv_extensions says:

    Interactions with ARB_shader_ballot and SPV_KHR_shader_ballot:

        When using these extensions the following GLSL -> SPIR-V mapping is used:

        ...
        * in uint gl_SubGroupInvocationARB; -> SubgroupLocalInvocationId,
        * uniform uint gl_SubGroupSizeARB;  -> SubgroupSize,

However,  the only capability listed for these enumerants is Kernel.

SubgroupLocalInvocationId and SubgroupSize also appear to be absent from SPV_KHR_shader_ballot.

**Comment by ianromanick** [comment]
I should amend that last statement.  SPV_KHR_shader_ballot says:

    (Add the SubgroupBallotKHR capability to SubgroupSize.)
    
    (Add the SubgroupBallotKHR capability to SubgroupLocalInvocationId.)

**Comment by dneto0** [comment]
This change appears in Rev 11 of the extension, at https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_shader_ballot.html 

If you agree, we can close this issue.

**Comment by johnkslang** [comment]
I have verified this in the current spec/headers.
