### ISSUE TITLE
Does BulitinSampleMask require CapabilitySampleRateShading?

### ISSUE THREAD

**Issue by ianromanick** [KhronosGroup/SPIRV-Headers#51]
Section 3.20 (Decoration) of the SPIR-V spec lists `SampleRateShading` in the row for `SampleMask`, and the SPIR-V validator checks for this.  However, https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/1.2/spirv.core.grammar.json says:

    {
          "enumerant" : "SampleMask",
          "value" : 20,
          "capabilities" : [ "Shader" ]
    },

In desktop OpenGL, `gl_SampleMaskIn` does not require sample rate shading, but `gl_SampleMask` (the output) does.  I don't know off the top of my head how this is exposed in Vulkan. Given the disagreement among the various specs, it's not 100% clear what the correct action for a SPIR-V generator is.

I don't think it's worth the effort to have different capabilities for the input and output in SPIR-V.  If others agree, then `spirv.core.grammar.json` should be updated to list the `SampleRateShading` dependency.  My code for emitting decorations and setting the necessary capabilities is generated directly from the JSON, so, whatever the conclusion, that file needs to be correct.

**Comment by dneto0** [comment]
This has flipped a couple of times, as logged in the spec revision history.

* In 1.0 Rev 3, SampleMask was made to depend on SampleRateShading
https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_changes_from_version_1_00_revision_2  

* In 1.0 Rev 12, SampleMask was made to depend only on Shader.  See https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_changes_from_version_1_00_revision_11

The current 1.2 spec shows SampleMask as enabled by Shader.  That matches the JSON grammar file.

**Comment by johnkslang** [comment]
The current consensus is pretty clear and has lasted a long time. From the spec:

> * Khronos SPIR-V issue #182: The SampleMask built in does not depend on SampleRateShading, only Shader.
