### ISSUE TITLE
SPV_AMD_shader_fragment_mask capability token name ambiguous

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/SPIRV-Headers#52]
The [SPV_AMD_shader_fragment_mask](https://www.khronos.org/registry/spir-v/extensions/AMD/SPV_AMD_shader_fragment_mask.html) defines a token `CapabilityFragmentMask`,
but the [SPIR-V Specification](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#Capability) defines `FragmentMaskAMD`.

**Comment by dneto0** [comment]
Thanks for raising this issue.  They both are assigned the number 5010.  SPIR-V is officially a binary format so it's the number that really counts for compatibility.

Also, tokens introduced by vendor extensions should always have the vendor's suffix on the name.  So I would think that FragmentMaskAMD is the correct token name.  (Each language-specific header may add a prefix depending on token scoping needs.  E.g. The C language header uses SpvCapabilityFragmentMaskAMD.  https://github.com/KhronosGroup/SPIRV-Headers/blob/master/include/spirv/1.0/spirv.h#L649)

Hi @amdrexu : Can you fix the AMD extension spec?

**Comment by dneto0** [comment]
I filed Khronos internal issue 240 to track publication of a fix.

**Comment by krOoze** [comment]
@ Good, in
https://github.com/KhronosGroup/Vulkan-Docs/pull/613
I went with `FragmentMaskAMD ` as well.

**Comment by amdrexu** [comment]
Thank you. We will fix it.

**Comment by johnkslang** [comment]
This has been fixed.
