### ISSUE TITLE
function recursion and re-entry

### ISSUE THREAD

**Issue by sylware** [KhronosGroup/SPIRV-Headers#53]
Hi,
Just skimmed through spirv 1.2 specs and it seems that function recursion and re-entry is now allowed?

Recursion and call-graph re-entry must be detected for those functions because they cannot afford a static allocation of vector registers. It seems related to the control flow graph dynamic thingies.
Roughly speaking:
 - each recursive function (or recursive call-subgraph) will need a stack in GPU memory for each vector unit-->this will hurt badly performance.
 - 're-entered' functions would need a new set of vector unit registers for each re-entry.

Did I miss something? Or do we go CPU-like (stack) vector units in GPU? (namely, we ate the bullet)

**Comment by johnkslang** [comment]
The client API execution-environment specifications should prevent recursion if they do not want it.

Vulkan, OpenGL, and OpenCL should all be doing so in the their specifications.

**Comment by sylware** [comment]
For instance, a vulkan client program would need to deal with _both_ a vulkan
client API which will support recursion/call-graph re-entry or one which will
support no recursion or re-entry (based on GPU specs)?

I do apologize for this question (I should look in vulkan API specs), but which
set of vulkan API functions are supposed to deal with this? 

It means the application developers will have to write shaders for both models?

I'm sure I miss something important here... because having RAM stacks for all
vector units of moderns GPUs will probably destroy performance, or the hardware
guys did benchmark this in realistic workload?

**Comment by sylware** [comment]
Ate the bullet, got into latest vulkan specs:
appendix A for gfx/compute shaders: "Recursion: The static function-call graph for an entry point must not contain cycles."

In my memory, this was defined in spirv specs, gfx shader constraints. I guess
I forgot where this was actually defined. I got scared by the cfg dynamic
thingies in spir-v 1.2 specs.

**Comment by dneto0** [comment]
As @johnkslang said, the client API environments forbid recursion in the call graph.  Also, there is no equivalent of function pointers.   So if you're writing tools for the client APIs or implementations of those APIs you only have to handle the simple case.  But saying so is outside the SPIR-V spec itself, strictly speaking.

**Comment by sylware** [comment]
On Wed, Nov 22, 2017 at 03:03:54AM +0000, David Neto wrote:
> As @johnkslang said, the client API environments forbid recursion in the call
> graph.  Also, there is no equivalent of function pointers.   So if you're
> writing tools for the client APIs or implementations of those APIs you only
> have to handle the simple case.  But saying so is outside the SPIR-V spec
> itself, strictly speaking.

To improve on that, a reader (implementor to became) should be presented all
those critical/major points of implementation in a "very highlighted way".

Because one of the first "major" things to be sorted out is the CFG (Control Flow
Graph).

I'm aware of the pb because I started to write one of my own (for AMD GCN GPUs)
because I know that _working_ alternatives is critical to maintain freedom in
the software world. but I did burn myself on the "block ordering soup" (please,
do consider seriously defining a canonical block ordering). If my IRL issues
are solved somehow one day, I may attempt to code an alternative implementation
again.
