### ISSUE TITLE
VariablePointers conflicting with logical addressing

### ISSUE THREAD

**Issue by BNieuwenhuizen** [KhronosGroup/SPIRV-Headers#55]
The VariablePointers and VariablePointersStorageBuffer capabilities allow OpPtrAccessChain. However per the universal validation rules, a pointer cannot be the result of an OpPtrAccessChain if logical adressing is used. Which makes it pretty useless for the VK_KHR_variable_pointers vulkan extension.

Furthermore, the only reference to these capabilities I see is that they allow OpPtrAccessChain, making it unclear in what situations it is allowed and with what restrictions. I can't even tell how VariablePointers and VariablePointersStorageBuffer are supposed to be different.

I used the 1.2 version of the spec for checking this issue.

**Comment by johnkslang** [comment]
The extension adds this as new functionality, incrementally over version 1.2 of the specification. We've been showing token reservations in the specifications in earlier versions than when the extension is actually incorporated, and that needs to be made more clear. The extension is not incorporated in version 1.2.

Can you check the extension language itself, and based on that see if the issues are actually present?

**Comment by BNieuwenhuizen** [comment]
Seems I was just missing the separate extensions documents, and given that the main spec referred to it was assuming the extensions were part of the main spec. No wonder the extension looked very incomplete to me.

Thanks!
