### ISSUE TITLE
Is it valid structured control flow: switch-case goto loop merge

### ISSUE THREAD

**Issue by lifpan** [KhronosGroup/SPIRV-Headers#75]
[switchcase_goto_loop_merge.spv.txt](https://github.com/KhronosGroup/SPIRV-Headers/files/2179180/switchcase_goto_loop_merge.spv.txt)

The switch-case is inside the loop. It branches from switch-case to loop merge block.
I think it's invalid, but I'd like someone to confirm it. Is there some validator that can check it?

        %808 = OpLabel
               OpLoopMerge **%809** %810 None
               OpBranch %811
        ...
               OpSelectionMerge %813 None
               OpSwitch %849 %814 0 %815 1 %816 2 %817
        %814 = OpLabel
               OpBranch **%809**
        %815 = OpLabel
        %818 = OpLoad %211 %213
        %819 = OpLoad %215 %217
        %820 = OpSampledImage %219 %818 %819
        %822 = OpImageSampleImplicitLod %27 %820 %670
               OpBranch **%809**
        ...
        %813 = OpLabel
               OpUnreachable
        %810 = OpLabel
               OpBranch %808
        %809 = OpLabel
        ...

**Comment by johnkslang** [comment]
The SPIRV-Tools validator (spirv-val) aspires to correctly validate control flow. Having said that, there are some corner cases we are refining inside Khronos, and there might also be some corner cases not yet complete in the validation.

@alan-baker might have something specific to add for this particular case, otherwise I expect we will have complete formalism soon, followed soon by complete implementation.

But, perhaps your case is simple, if it violates the following rule from section 2.11 of the specification:

> * the merge block declared by a header block cannot be a merge block declared by any other header block

**Comment by lifpan** [comment]
I think the rule it violates is:
> • the only blocks in a construct that can branch outside the construct are
> – a block branching to the construct’s merge block

**Comment by alan-baker** [comment]
This case looks correct to me. Each switch statement is embedded within a loop (albeit a trivial one). The section @lifpan refers to is:
```
the only blocks in a construct that can branch outside the construct are
* a block branching to the construct’s merge block
* a block branching from one case construct to another, for the same OpSwitch
* a continue block for the innermost loop it is nested inside of
* a break block for the innermost loop it is nested inside of
* a return block
```

In this case, the case constructs exercise the 4th rule of breaking to the merge of the innermost loop it is nested within.

I've attached the CFG for reference.

![switchcase_goto_loop_merge](https://user-images.githubusercontent.com/33432579/42573071-19206266-84e9-11e8-9117-d0103a9c6435.png)

**Comment by lifpan** [comment]
I see. This CFG picture is wonderful!

**Comment by alan-baker** [comment]
FYI, I produced that using SPIR-V Tools' spirv-cfg executable. It produces a dot file from a SPIR-V binary.

**Comment by dylanede** [comment]
@alan-baker, that paragraph starting with "the only blocks in a construct..." doesn't seem to exist any more in the standard. Does that mean this no longer applies, or has it been rephrased?

**Comment by alan-baker** [comment]
It was reworded. The following snippet contains the equivalent statement about break blocks.
>The above structured control-flow constructs must satisfy the following rules:
> * if a construct contains another header block, it also contains that header’s corresponding merge block if that merge block is reachable in the CFG
> * a continue construct must include its loop’s back-edge block
> * a break block is valid only for the innermost loop it is nested inside of
> ...

**Comment by dylanede** [comment]
OK. Slightly off-topic, but since that rewording, it seems like it is no longer disallowed to branch out of a construct through a means that is not a continue or break block, as long as the branch is not to an outer `OpSwitch` merge block. Am I missing something?

**Comment by alan-baker** [comment]
The spec was reworded so that all the exits must be "structured". That section now enumerates the structured exits. So you still can't have arbitrary exits from a construct.
