### ISSUE TITLE
Tagging a stable version

### ISSUE THREAD

**Issue by dholm** [KhronosGroup/SPIRV-Headers#76]
Would you mind tagging a recent commit with a stable version (no "rc") of SPIRV-Headers so that it can be packaged in Homebrew?

**Comment by cmarcelo** [comment]
It seems reasonable to tag the SPIRV releases.

@dneto0 would that be possible?

**Comment by johnkslang** [comment]
Yes, I agree. Will try to work out a scheme on next change. Sorry I dropped the ball on this earlier.

Curious: how is the addition of tokens breaking things?

**Comment by johnkslang** [comment]
SPIR-V 1.3, revision 7 is now published, based on the current set of headers, which are now tagged as 1.3.7. Will aim to do this for each release.
