### ISSUE TITLE
Does the exit branch for a loop need to be an OpBranchConditional?

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/SPIRV-Headers#77]
Consider something like this
![](https://i.imgur.com/MFJ2yug.png)

Where `bb6` exits the loop with `bb17`. I assume that would be illegal because only `OpBranchConditional` and `OpBranch` can be "annotated" with an `OpLoopMerge`.

Couldn't it be relaxed so that an `OpSwitch` can also become a LoopHeader if the switch has two targets or less? *Default + 1 target branch*

**Comment by johnkslang** [comment]
I don't think there is a fundamental problem preventing an exit branch from being a switch. It may just be a way of simplifying the system, but I suspect it could be relaxed.

**Comment by johnkslang** [comment]
See also #78.

To be more clear, there are numerous ways to exit a construct, and no requirement that it must be an OpBranchConditional.
