### ISSUE TITLE
What are the merge blocks if a loop has multiple exits?

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/SPIRV-Headers#78]
![](https://i.imgur.com/S8rg6VQ.png)

This is generated from glslang with

```
float test(float[2] arr) {
    uint i = 0;
    float sum = 42;
    while(true) {
        sum += 1.0;
        i+=1;
        if(i == 100){
            return sum;
        }
    }
    return sum;
}
```

The way I implemented it is: If the loop headers terminator is an `OpBranch`, I look for the first  branch where one of the targets exits the loop. Then for this branch I don't generate an `SelectionMerge`. And one of its targets is the loop merge.

But what if we have multiple exits like in the image above? 

For example for `%22`. Is `%38` correct? Would `%37` also be a correct merge block? Or do successive branches (like `%22) need to have the merge block inside the loop?

**Comment by johnkslang** [comment]
Each structured control-flow construct should have exactly one merge block. There is one header (or entry) that starts the construct, and it has one merge point.

If, inside a construct, you have exits to merge points of the construct (or constructs it is nested in, or Return), those exits are merging/reconverging exits and hence not new points of divergence. Only new points of divergence, which create new constructs, are allowed to declare new merge blocks. Blocks that branch either to exit a construct or to keep going linearly within the construct do not declare new merge blocks.
