### ISSUE TITLE
Commentary instruction

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/SPIRV-Headers#81]
I'm writing a Maxwell -> SPIR-V decompiler for an emulator. For debugging purposes, commenting the current instruction to be decompiled is useful because it let's you know what it's trying to do. That's easy to do in GLSL, but in SPIR-V there's no such thing. 

To workaround this issue what I'm currently doing is emitting an `OpUndef %void` and then naming it, that way it ends up being visible in `spirv-dis`'s output:
```
               OpName %12_MUFU_0x5080000000470003 "12_MUFU_0x5080000000470003"
               OpName %13_IPA_0xe043ff880037ff00 "13_IPA_0xe043ff880037ff00"

...

%12_MUFU_0x5080000000470003 = OpUndef %void
        %315 = OpLoad %float %gpr0
        %316 = OpLoad %float %gpr4
        %317 = OpFDiv %float %float_1 %315
               OpStore %gpr3 %317
%13_IPA_0xe043ff880037ff00 = OpUndef %void
        %321 = OpLoad %float4 %input_attr_0
        %322 = OpCompositeExtract %float %321 0
               OpStore %gpr0 %322
```

What I want is something that can be easily dropped from the binary like `OpLine`. In my opinion a `OpComment "This is a commentary"` would be optimal (`OpString` in a function body is illegal).

As a note, I'm emitting SPIR-V directly to binary so `spirv-as` commentaries won't work (and they wouldn't be visible in debugging tools).

**Comment by johnkslang** [comment]
Does the decoration `HlslSemanticGOOGLE` from [SPV_GOOGLE_hlsl_functionality1](https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/GOOGLE/SPV_GOOGLE_hlsl_functionality1.asciidoc) solve this problem?

**Comment by ReinUsesLisp** [comment]
If it is allowed to be in a function body and not just in the annotations section, then it solves it. It'd look like:
```asm
               OpHlslSemanticGOOGLE "12 MUFU (0x5080000000470003)"
        %315 = OpLoad %float %gpr0
        %316 = OpLoad %float %gpr4
        %317 = OpFDiv %float %float_1 %315
               OpStore %gpr3 %317
               OpHlslSemanticGOOGLE "13 IPA (0xe043ff880037ff00)"
        %321 = OpLoad %float4 %input_attr_0
        %322 = OpCompositeExtract %float %321 0
               OpStore %gpr0 %322
```

That being said, SPV_GOOGLE_hlsl_functionality1 doesn't seem to be widely supported.

**Comment by johnkslang** [comment]
> If it is allowed to be in a function body ...

It would be used with `OpDecorateStringGOOGLE` to decorate an arbitrary `<id>`. The decorated `<id>` can be anywhere, while the decoration instructions must stay in the annotation section. So, for example, if you could tie the string to `%315`, then early on you would issue:

```
OpDecorateStringGOOGLE %315 DecorationHlslSemanticGOOGLE "12 MUFU (0x5080000000470003)"
```

This would then be insensitive to code ordering.

> SPV_GOOGLE_hlsl_functionality1 doesn't seem to be widely supported 

The point is if we design a new thing instead, it will start out even less widely supported. If we can use the same mechanism (and drop the "HLSL" denotation), we'd have multiple reasons to adopt, giving even more widespread adoption than either would have on its own.

**Comment by ReinUsesLisp** [comment]
Yes, that would solve the issue. I don't like the link to `%315` but I can see why it's needed.
